version: '2'

services:
  openresty:
    image: openresty/openresty:alpine
    volumes:
      - ./openresty/conf.d/:/etc/nginx/conf.d/
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "${NGINX_LOG_VOLUME}:/var/log/nginx"
    environment:
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    ports:
      - "8222:8222"
      - "3000:3000"

  siu:
    image: qyvlik/siu:latest
    environment:
      - SPRING_REDIS_DATABASE=redis
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

  redis:
    image: redis:5

  grafana:
    image: grafana/grafana:6.3.0
    volumes:
      - grafana_volumes:/var/lib/grafana
    environment:
      #- GF_SERVER_DOMAIN=${GRAFANA_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=grafana
      - GF_SERVER_STATIC_ROOT_PATH=public
      - GF_SECURITY_ALLOW_EMBEDDING=true

volumes:
  grafana_volumes:
